var serverUrlGetMyBox = "http://andy-lin.info:20003/api/getBox" ;
var serverUrlSetLeader = "http://andy-lin.info:20003/api/setCapital" ;
var serverUrlReleaseMonster = "http://andy-lin.info:20003/api/releaseMonster";
var serverUrlBattleWinGetNewMonster = "http://andy-lin.info:20003/api/addMonsterInBox";
var serverUrlBattlePVPWin ;
var serverUrlBattlePVPSovcket = "http://localhost:20005" ;
var serverUrlGetFriendList = "http://andy-lin.info:20003/api/getFriendList";
var serverUrlAddNewFriend = "http://andy-lin.info:20003/api/addFriend";
var serverUrlFirstLoginAddNewUser = "http://andy-lin.info:20003/user/add";
var serverUrlLogin = "http://andy-lin.info:20003/user/login"; 